/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00201d",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#2e150b",
        "on-background": "#1a1c1b",
        "inverse-primary": "#accdc7",
        "on-surface": "#1a1c1b",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-container": "#4b2d22",
        "surface-tint": "#45645f",
        "tertiary-fixed-dim": "#ebbcac",
        "surface-container-low": "#f4f4f2",
        "primary-fixed": "#c8e9e3",
        "surface-variant": "#e2e3e1",
        "background": "#f9f9f7",
        "secondary-container": "#d8e5e2",
        "secondary-fixed": "#d8e5e2",
        "surface-container-highest": "#e2e3e1",
        "surface-container-high": "#e8e8e6",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#414847",
        "secondary-fixed-dim": "#bcc9c6",
        "on-error": "#ffffff",
        "on-secondary-container": "#5b6764",
        "surface-bright": "#f9f9f7",
        "on-secondary-fixed-variant": "#3d4947",
        "on-tertiary-fixed-variant": "#603f33",
        "inverse-on-surface": "#f1f1ef",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#2e4c48",
        "primary-container": "#1b3a36",
        "outline-variant": "#c1c8c6",
        "primary-fixed-dim": "#accdc7",
        "secondary": "#55615e",
        "surface-dim": "#dadad8",
        "primary": "#032421",
        "inverse-surface": "#2f3130",
        "tertiary": "#32180f",
        "surface-container": "#eeeeec",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#be9385",
        "outline": "#717977",
        "on-secondary-fixed": "#121e1c",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#84a49e",
        "surface": "#f9f9f7",
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
        "serif": ["Newsreader", "serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
